import { describe, expect, test } from "bun:test"
import { mkdtemp, rm } from "node:fs/promises"
import { tmpdir } from "node:os"
import { mkdir } from "node:fs/promises"
import path from "node:path"
import {
  domainLabelFromId,
  ensureSkillDomainsInRegistry,
  readSkillDomainsRegistry,
  skillDomainHintsFromAssignments,
  syncSkillDomainsRegistryFromByDomain,
  unknownSkillDomainIds,
} from "../src/skills/domains.ts"
import { writeAutoCuratorSummary } from "../src/skills/curator-summary.ts"
import { resolveProjectPath } from "../src/paths.ts"

describe("skill domains registry automation", () => {
  test("domainLabelFromId title-cases hyphenated ids", () => {
    expect(domainLabelFromId("code-agent-claude")).toBe("Code Agent Claude")
  })

  test("unknownSkillDomainIds lists assignment ids missing from registry", () => {
    expect(
      unknownSkillDomainIds({ worker: "docs", other: "new-domain" }, [{ id: "docs", label: "Docs" }]),
    ).toEqual(["new-domain"])
  })

  test("ensureSkillDomainsInRegistry adds missing domains from assignments", async () => {
    const dir = await mkdtemp(path.join(tmpdir(), "gh-domains-"))
    try {
      const hints = skillDomainHintsFromAssignments(
        { "node-a": "docs", "node-b": "docs" },
        [{ id: "docs", label: "Documentation", description: "README and docs tasks" }],
      )
      const sync = await ensureSkillDomainsInRegistry(dir, hints)
      expect(sync.added).toEqual(["docs"])
      expect(sync.updated).toEqual([])

      const entries = await readSkillDomainsRegistry(dir)
      expect(entries).toEqual([
        { id: "docs", label: "Documentation", description: "README and docs tasks" },
      ])
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  test("ensureSkillDomainsInRegistry auto-labels unknown domain ids", async () => {
    const dir = await mkdtemp(path.join(tmpdir(), "gh-domains-auto-"))
    try {
      const sync = await ensureSkillDomainsInRegistry(
        dir,
        skillDomainHintsFromAssignments({ worker: "new-domain-id" }),
      )
      expect(sync.added).toEqual(["new-domain-id"])
      const entries = await readSkillDomainsRegistry(dir)
      expect(entries[0]?.label).toBe("New Domain Id")
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  test("syncSkillDomainsRegistryFromByDomain discovers dirs", async () => {
    const dir = await mkdtemp(path.join(tmpdir(), "gh-domains-sync-"))
    try {
      const docsDir = resolveProjectPath(dir, ".gatehouse/skills/by-domain/docs")
      await mkdir(docsDir, { recursive: true })
      await Bun.write(path.join(docsDir, ".keep"), "")
      const sync = await syncSkillDomainsRegistryFromByDomain(dir)
      expect(sync.added).toEqual(["docs"])
      expect((await readSkillDomainsRegistry(dir)).map((entry) => entry.id)).toEqual(["docs"])
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })
})

describe("auto curator summary", () => {
  test("writeAutoCuratorSummary includes node report excerpts", async () => {
    const dir = await mkdtemp(path.join(tmpdir(), "gh-curator-summary-"))
    const missionId = "m-auto"
    const nodeId = "node-doc"
    try {
      const extractRel = `.gatehouse/missions/${missionId}/reports/skills/${nodeId}-extract.md`
      const verifyRel = `.gatehouse/missions/${missionId}/reports/skills/${nodeId}-verify.md`
      await Bun.write(resolveProjectPath(dir, extractRel), "# Extract\n\nCreated docs skill.\n")
      await Bun.write(resolveProjectPath(dir, verifyRel), "# Verify\n\npassed: true\n")

      const summaryRel = await writeAutoCuratorSummary(dir, missionId, [nodeId])
      const text = await Bun.file(resolveProjectPath(dir, summaryRel)).text()
      expect(text).toContain("Auto-generated by Gatehouse")
      expect(text).toContain("Created docs skill.")
      expect(text).toContain("passed: true")
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })
})
