import { mkdir } from "node:fs/promises"
import path from "node:path"
import {
  curatorSkillSummaryRelPath,
  curatorSummaryRelPath,
  resolveProjectPath,
  skillVerifyReportRelPath,
} from "../paths.ts"
import { formatSkillDomainsRegistry, readSkillDomainsRegistry } from "./domains.ts"
import { readLocaleSync } from "../locale.ts"

async function readReportExcerpt(projectDirectory: string, relPath: string, maxLines = 12) {
  const abs = resolveProjectPath(projectDirectory, relPath)
  if (!(await Bun.file(abs).exists())) return undefined
  const text = await Bun.file(abs).text()
  const lines = text.trim().split("\n").slice(0, maxLines)
  if (lines.length === 0) return undefined
  return lines.join("\n")
}

export async function writeAutoCuratorSummary(
  projectDirectory: string,
  missionId: string,
  nodeIds: string[],
) {
  const locale = readLocaleSync(projectDirectory)
  const lines = [
    `# Curator skill summary · Mission ${missionId}`,
    "",
    "_Auto-generated by Gatehouse after extract + verify._",
    "",
    "## Node reports",
    "",
  ]

  for (const nodeId of nodeIds) {
    const extractRel = curatorSkillSummaryRelPath(missionId, nodeId)
    const verifyRel = skillVerifyReportRelPath(missionId, nodeId)
    lines.push(`### ${nodeId}`, "")
    const extractExcerpt = await readReportExcerpt(projectDirectory, extractRel)
    if (extractExcerpt) {
      lines.push("#### Extract", "", extractExcerpt, "")
    }
    const verifyExcerpt = await readReportExcerpt(projectDirectory, verifyRel)
    if (verifyExcerpt) {
      lines.push("#### Verify", "", verifyExcerpt, "")
    }
  }

  const domains = await readSkillDomainsRegistry(projectDirectory)
  lines.push("## Domains registry", "", formatSkillDomainsRegistry(domains, locale), "")

  const summaryRel = curatorSummaryRelPath(missionId)
  const summaryAbs = resolveProjectPath(projectDirectory, summaryRel)
  await mkdir(path.dirname(summaryAbs), { recursive: true })
  await Bun.write(summaryAbs, `${lines.join("\n").trimEnd()}\n`)
  return summaryRel
}
